const ACTIONS = {
    REGISTER_USER : "REGISTER_USER",
    REGISTER_USER_SUCCESS: "REGISTER_USER_SUCCESS",
    REGISTER_USER_FAIL: "REGISTER_USER_FAIL",
    LOGIN_USER : "LOGIN_USER",
    LOGIN_USER_SUCCESS: "LOGIN_USER_SUCCESS",
    LOGIN_USER_FAIL: "LOGIN_USER_FAIL",
    GET_PROFILE: "GET_PROFILE",
    GET_PROFILE_SUCCESS: "GET_PROFILE_SUCCESS",
    GET_PROFILE_FAIL : "GET_PROFILE_FAIL",
    GET_ALL_USERS: "GET_ALL_USERS",
    GET_ALL_USERS_SUCCESS : "GET_ALL_USERS_SUCCESS",
    GET_ALL_USERS_FAIL: "GET_ALL_USERS_FAIL",
    


    LOGOUT_USER: "LOGOUT_USER"

}

export default ACTIONS;