const ACTIONS = {
    USER_LOADING :'USER_LOADING',
    REGISTER_SUCCESS : "REGISTER_SUCCESS",
    REGISTER_FAIL : "REGISTER_FAIL",
    LOGIN_SUCCESS: "LOGIN_SUCCESS",
    LOGIN_FAIL: "LOGIN_FAIL",
    SET_ALERT: "SET_ALERT",
    REMOVE_ALERT: "REMOVE_ALERT",
    GET_AUTH_USER_SUCCESS: "GET_AUTH_USER_SUCCESS",
    GET_AUTH_USER_FAIL: "GET_AUTH_USER_FAIL",
    LOGOUT: "LOGOUT"
}

export default ACTIONS;